services:
  task-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mohamedahegazy/task-backend:latest
    container_name: task-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
      - APP_ENV=local
      - CORS=http://localhost:5173
      - SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
